### ISSUE TITLE
It's wrong

### ISSUE THREAD

**Issue by ChildishGiant** [sonnylazuardi/are-you-github-pro#1]
So it's saying I have pro when I don't.
![image](https://user-images.githubusercontent.com/13716824/51511221-4ba96b80-1df8-11e9-8755-bad4c87eaa5d.png)

![image](https://user-images.githubusercontent.com/13716824/51511247-64198600-1df8-11e9-9924-025ca690659e.png)

![image](https://user-images.githubusercontent.com/13716824/51511263-7398cf00-1df8-11e9-874c-5504a4deda76.png)

**Comment by ChildishGiant** [comment]
I was gonna direct you to the github user api but they don't seem to have data on that. Well that sucks.

**Comment by sonnylazuardi** [comment]
@ChildishGiant I updated the dom checking, should be correct now. thanks for pointing this out

**Comment by ChildishGiant** [comment]
Yep, all fixed on my end too :)
